### ISSUE TITLE
MenuMaker error 

### ISSUE THREAD

**Issue by lpvm** [voidlinux/void-packages#5984]
It was working in version 0.99.9_1, not now.

```
$ mmaker --version
MenuMaker 0.99.10

$ mmaker fluxbox
Traceback (most recent call last):
  File "/sbin/mmaker", line 3, in <module>
    import MenuMaker.CLI
  File "/usr/share/menumaker/MenuMaker/CLI.py", line 204, in <module>
    desktop = Prophet.Desktop.scan()
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 152, in scan
    result.append(App(os.path.join(w[0], x)))
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 258, in __new__
    self.__setup__(desktop)
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 281, in __setup__
    super(App, self).__setup__()
  File "/usr/share/menumaker/Prophet/__init__.py", line 255, in __setup__
    self.setKeywords()
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 306, in setKeywords
    self.keywords = KwS(cats)
  File "/usr/share/menumaker/Keywords.py", line 42, in __init__
    xargs.append(Keyword(x))
  File "/usr/share/menumaker/Keywords.py", line 14, in __init__
    for x in s.split():
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by asergi** [comment]
https://sourceforge.net/p/menumaker/bugs/8/

**Comment by cr6void** [comment]
@lpvm Do you still have this problem with menumaker ?

On my system it works fine:

`$ mmaker fluxbox`

=> The file `~/.fluxbox/menu` is created.

**Comment by maxice8** [comment]
works fine here, can close ?

**Comment by lpvm** [comment]
It still returns an error in my system:

```
$ mmaker --version
MenuMaker 0.99.10
```


```
$ mmaker fluxbox
Traceback (most recent call last):
  File "/usr/bin/mmaker", line 3, in <module>
    import MenuMaker.CLI
  File "/usr/share/menumaker/MenuMaker/CLI.py", line 204, in <module>
    desktop = Prophet.Desktop.scan()
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 152, in scan
    result.append(App(os.path.join(w[0], x)))
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 258, in __new__
    self.__setup__(desktop)
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 281, in __setup__
    super(App, self).__setup__()
  File "/usr/share/menumaker/Prophet/__init__.py", line 255, in __setup__
    self.setKeywords()
  File "/usr/share/menumaker/Prophet/Desktop/__init__.py", line 306, in setKeywords
    self.keywords = KwS(cats)
  File "/usr/share/menumaker/Keywords.py", line 42, in __init__
    xargs.append(Keyword(x))
  File "/usr/share/menumaker/Keywords.py", line 14, in __init__
    for x in s.split():
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by maxice8** [comment]
sorry can't help here it is working fine.

**Comment by lpvm** [comment]
Ok, then close it.
I'm not using it, just edit my menu entries by hand.

Thanks!
