### ISSUE TITLE
binutils-2.29 + glibc-2.26 for cross-* 

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#7284]
I have an update for `binutils-2.29` also for `cross-*` in the queue.
The `cross-*-gnu*` pkgs will be updated to `glibc-2.26` at the same time.
I'm running tests locally to see if everything is ok before pushing it.

I'll also try to move the conflicting `/usr/lib/libcc1.so.*` to the `$sysroot/usr/lib` directory.
That shouldn't cause trouble since the native `/usr/lib/libcc1.so.*` is good enough for gdb as far as I can tell [from the comments on the net](https://gcc.gnu.org/ml/gcc/2015-01/msg00191.html)

**Comment by pullmoll** [comment]
Building `cross-i686-pc-linux-gnu` fails with:
```
In file included from ../../../gcc-6.3.0/libgcc/unwind-dw2.c:401:0:
./md-unwind-support.h: In function 'x86_fallback_frame_state':
./md-unwind-support.h:141:18: error: field 'uc' has incomplete type
  struct ucontext uc;
                  ^~
```
So it looks like `gcc-6.3.0` needs another patch for `glibc-2.26` :-(

**Comment by ebfe** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=NEWS;hb=HEAD

> * The ucontext_t type no longer has the name struct ucontext.  This changes
>   the C++ name mangling for interfaces involving this type.

**Comment by pullmoll** [comment]
Yup @ebfe, just found that. I think a quick and dirty `sed` in post_extract() replacing `struct ucontext` with `struct ucontext_t` will do. Giving it a try now.

**Comment by ebfe** [comment]
This will likely break a few other packages as well

**Comment by pullmoll** [comment]
More fun with gcc-6.3.0
```
/builddir/gcc-6.3.0/libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:270:22: error: aggregate 'sigaltstack handler_stack' has incomplete type and cannot be defined
   struct sigaltstack handler_stack;
                      ^~~~~~~~~~~~~
```

*sigh*

**Comment by ebfe** [comment]
More breakage due to SIGUNUSED removal.

**Comment by pullmoll** [comment]
... and this was when things began to turn from bad to worse.
Here's what I have so far.

`srcpkgs/gcc/fix-glibc-struct_ucontext_t.patch`
```
Cherry picked the gcc commit 14c2f22a1877f6b60a2f7c2f83ffb032759456a6
changes and edited to work with patch -p0

--- libgcc/config/aarch64/linux-unwind.h
+++ libgcc/config/aarch64/linux-unwind.h
@@ -55,7 +55,7 @@ aarch64_fallback_frame_state (struct _Unwind_Context *context,
   struct rt_sigframe
   {
     siginfo_t info;
-    struct ucontext uc;
+    ucontext_t uc;
   };
 
   struct rt_sigframe *rt_;
--- libgcc/config/alpha/linux-unwind.h
+++ libgcc/config/alpha/linux-unwind.h
@@ -51,7 +51,7 @@ alpha_fallback_frame_state (struct _Unwind_Context *context,
     {
       struct rt_sigframe {
 	siginfo_t info;
-	struct ucontext uc;
+	ucontext_t uc;
       } *rt_ = context->cfa;
       sc = &rt_->uc.uc_mcontext;
     }
--- libgcc/config/bfin/linux-unwind.h
+++ libgcc/config/bfin/linux-unwind.h
@@ -52,7 +52,7 @@ bfin_fallback_frame_state (struct _Unwind_Context *context,
 	void *puc;
 	char retcode[8];
 	siginfo_t info;
-	struct ucontext uc;
+	ucontext_t uc;
       } *rt_ = context->cfa;
 
       /* The void * cast is necessary to avoid an aliasing warning.
--- libgcc/config/i386/linux-unwind.h
+++ libgcc/config/i386/linux-unwind.h
@@ -58,7 +58,7 @@ x86_64_fallback_frame_state (struct _Unwind_Context *context,
   if (*(unsigned char *)(pc+0) == 0x48
       && *(unsigned long long *)(pc+1) == RT_SIGRETURN_SYSCALL)
     {
-      struct ucontext *uc_ = context->cfa;
+      ucontext_t *uc_ = context->cfa;
       /* The void * cast is necessary to avoid an aliasing warning.
          The aliasing warning is correct, but should not be a problem
          because it does not alias anything.  */
@@ -138,7 +138,7 @@ x86_fallback_frame_state (struct _Unwind_Context *context,
 	siginfo_t *pinfo;
 	void *puc;
 	siginfo_t info;
-	struct ucontext uc;
+	ucontext_t uc;
       } *rt_ = context->cfa;
       /* The void * cast is necessary to avoid an aliasing warning.
          The aliasing warning is correct, but should not be a problem
--- libgcc/config/m68k/linux-unwind.h
+++ libgcc/config/m68k/linux-unwind.h
@@ -33,7 +33,7 @@ see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
 /* <sys/ucontext.h> is unfortunately broken right now.  */
 struct uw_ucontext {
 	unsigned long	  uc_flags;
-	struct ucontext  *uc_link;
+	ucontext_t	 *uc_link;
 	stack_t		  uc_stack;
 	mcontext_t	  uc_mcontext;
 	unsigned long	  uc_filler[80];
--- libgcc/config/nios2/linux-unwind.h
+++ libgcc/config/nios2/linux-unwind.h
@@ -38,7 +38,7 @@ struct nios2_mcontext {
 
 struct nios2_ucontext {
   unsigned long uc_flags;
-  struct ucontext *uc_link;
+  ucontext_t *uc_link;
   stack_t uc_stack;
   struct nios2_mcontext uc_mcontext;
   sigset_t uc_sigmask;	/* mask last for extensibility */
--- libgcc/config/pa/linux-unwind.h
+++ libgcc/config/pa/linux-unwind.h
@@ -80,7 +80,7 @@ pa32_fallback_frame_state (struct _Unwind_Context *context,
   struct sigcontext *sc;
   struct rt_sigframe {
     siginfo_t info;
-    struct ucontext uc;
+    ucontext_t uc;
   } *frame;
 
   /* rt_sigreturn trampoline:
--- libgcc/config/sh/linux-unwind.h
+++ libgcc/config/sh/linux-unwind.h
@@ -82,7 +82,7 @@ sh_fallback_frame_state (struct _Unwind_Context *context,
     {
       struct rt_sigframe {
 	siginfo_t info;
-	struct ucontext uc;
+	ucontext_t uc;
       } *rt_ = context->cfa;
       /* The void * cast is necessary to avoid an aliasing warning.
          The aliasing warning is correct, but should not be a problem
--- libgcc/config/tilepro/linux-unwind.h
+++ libgcc/config/tilepro/linux-unwind.h
@@ -61,7 +61,7 @@ tile_fallback_frame_state (struct _Unwind_Context *context,
   struct rt_sigframe {
     unsigned char save_area[C_ABI_SAVE_AREA_SIZE];
     siginfo_t info;
-    struct ucontext uc;
+    ucontext_t uc;
   } *rt_;
 
   /* Return if this is not a signal handler.  */
--- libgcc/config/xtensa/linux-unwind.h
+++ libgcc/config/xtensa/linux-unwind.h
@@ -67,7 +67,7 @@ xtensa_fallback_frame_state (struct _Unwind_Context *context,
 
   struct rt_sigframe {
     siginfo_t info;
-    struct ucontext uc;
+    ucontext_t uc;
   } *rt_;
 
   /* movi a2, __NR_rt_sigreturn; syscall */
```

`srcpgks/gcc/patches/fix-struct_sigaltstack.patch`
```
--- libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc	2015-10-21 09:32:45.000000000 +0200
+++ libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc	2017-08-05 18:16:36.004549680 +0200
@@ -267,7 +267,7 @@
 
   // Alternate stack for signal handling.
   InternalScopedBuffer<char> handler_stack_memory(kHandlerStackSize);
-  struct sigaltstack handler_stack;
+  stack_t handler_stack;
   internal_memset(&handler_stack, 0, sizeof(handler_stack));
   handler_stack.ss_sp = handler_stack_memory.data();
   handler_stack.ss_size = kHandlerStackSize;

```

**Comment by ebfe** [comment]
Looks like all the "annoying to build" stuff (browsers that use google-breakpad etc.) is broken by the ucontext_t change too.

**Comment by pullmoll** [comment]
To me that suggests it's better to revert to glibc-2.25 and wait until things have settled, no?

The second patch above doesn't work or isn't sufficient:
```
/builddir/gcc-6.3.0/libsanitizer/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:274:47: error: cannot conv
ert 'stack_t*' to 'const sigaltstack*' for argument '1' to '__sanitizer::uptr __sanitizer::internal_sigaltstack(cons
t sigaltstack*, sigaltstack*)'
   internal_sigaltstack(&handler_stack, nullptr);
```

I'm going to have a beer or two and think about it before trying to continue... :beers:

**Comment by ebfe** [comment]
virtualbox-ose build broken too, that's a new one
```
In file included from /builddir/VirtualBox-5.1.24/src/VBox/ExtPacks/VBoxDTrace/include/VBoxDTraceTypes.h:36:0,   
                 from /builddir/VirtualBox-5.1.24/src/VBox/ExtPacks/VBoxDTrace/onnv/uts/common/sys/ctf_api.h:52, 
                 from /builddir/VirtualBox-5.1.24/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libctf/common/libctf.h:47,                                                                                                                
                 from /builddir/VirtualBox-5.1.24/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/dt_impl.h:40,                                                                                                            
                 from /builddir/VirtualBox-5.1.24/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/dt_aggregate.c:39:                                                                                                       
/usr/include/sys/ucontext.h:37:37: note: previous declaration of 'greg_t' was here                               
 __extension__ typedef long long int greg_t;            
                                     ^~~~~~
```

**Comment by pullmoll** [comment]
As a consequence of trying to fix the `libsanitizer/sanitizer_common/sanitizer_linux.{cc,h}` files by including `<signal.h>` I see follow up errors with conflicting declarations in `libsanitizer/tsan/tsan_interceptors.cc`. This is not easy to solve and all tries failed so far.

This also means gcc currently remains broken and bootstrapping fails.

**Comment by chneukirchen** [comment]
Try https://patches.openembedded.org/patch/141612/

**Comment by pullmoll** [comment]
I just found another source for a patch: [gcc commit 72edc2c02f8b4768ad660f46a1c7e2400c0a8e06](https://github.com/gcc-mirror/gcc/commit/72edc2c02f8b4768ad660f46a1c7e2400c0a8e06)

I'm trying that one here now.

**Comment by pullmoll** [comment]
Next one in the bootstrap: `xbps` in `bin/xbps-fbulk/main.c`
```
main.c: In Funktion »waitRunning«:
main.c:287:16: Fehler: Implizite Deklaration der Funktion »wait3« [-Werror=implicit-function-declaration]
  while ((pid = wait3(&status, flags, NULL)) < 0 && flags == 0)
                ^~~~~
main.c:287:2: Fehler: Geschachtelte extern-Deklaration von »wait3« [-Werror=nested-externs]
  while ((pid = wait3(&status, flags, NULL)) < 0 && flags == 0)
  ^~~~~
cc1: Alle Warnungen werden als Fehler behandelt
make[2]: *** [../../mk/prog.mk:47: main.o] Fehler 1
make[2]: Verzeichnis „/tmp/glibc-1/builddir/xbps-0.51/bin/xbps-fbulk“ wird verlassen
make[1]: *** [../mk/subdir.mk:3: all] Fehler 1
make[1]: Verzeichnis „/tmp/glibc-1/builddir/xbps-0.51/bin“ wird verlassen
make: *** [Makefile:15: all] Fehler 1
=> ERROR: xbps-0.51_18: failed to run do_build() at line 14.
```

It looks as if `#define _BSD_SOURCE` is no longer sufficient to make `/usr/include/sys/wait.h` define `wait3(2)`.

**Comment by chneukirchen** [comment]
```
       wait3():
           Since glibc 2.19:
               _DEFAULT_SOURCE || _XOPEN_SOURCE >= 500
```

**Comment by pullmoll** [comment]
Modifying main.c to `#define _DEFAULT_SOURCE` before including sys/wait.h gives the same error, though.

**Comment by pullmoll** [comment]
[Changelog for 2.26](https://abi-laboratory.pro/tracker/changelog/glibc/2.26/log.html) just tells `[21625] libc: wait3 namespace`

**Comment by chneukirchen** [comment]
http://sprunge.us/ddjQ works for me?

**Comment by chneukirchen** [comment]
It needs to be set before stdlib.h i think.

**Comment by pullmoll** [comment]
Yep, this works. Can you patch xbps and push?

**Comment by chneukirchen** [comment]
Done.

**Comment by pullmoll** [comment]
Darn. The full blown gcc built (including all target languages: go, java) failed.
```
/builddir/gcc-6.3.0/libjava/prims.cc: In function 'void _Jv_catch_fpe(int, siginfo_t*, void*)':
./include/java-signal.h:32:26: error: invalid use of incomplete type 'struct _Jv_catch_fpe(int, siginfo_t*, void*)::
ucontext'
   gregset_t &_gregs = _uc->uc_mcontext.gregs;    \
                          ^
/builddir/gcc-6.3.0/libjava/prims.cc:192:3: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
   HANDLE_DIVIDE_OVERFLOW;
   ^~~~~~~~~~~~~~~~~~~~~~
./include/java-signal.h:31:10: note: forward declaration of 'struct _Jv_catch_fpe(int, siginfo_t*, void*)::ucontext'
   struct ucontext *_uc = (struct ucontext *)_p;    \
          ^
/builddir/gcc-6.3.0/libjava/prims.cc:192:3: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
   HANDLE_DIVIDE_OVERFLOW;
   ^~~~~~~~~~~~~~~~~~~~~~
```

Since noone actually uses gcj, should we just disable it?

**Comment by chneukirchen** [comment]
gcj will be gone with gcc 7 anyway.

**Comment by pullmoll** [comment]
OTOH it's just the same `struct ucontext` to `ucontext_t` change which seems to be required. Trying.

**Comment by pullmoll** [comment]
The cross-* binutils configure seems to require `--with-system-zlib` now, or it tries to use a non existing `./../zlib` include path.

But the cross-* packages fail to build with `binutils-2.29` anyway because flex isn't detected.
`cross-x86_64-linux-musl`:
```
checking lex output file root... configure: error: cannot find output from flex; giving up
```

Next problem to track down and eliminate.

**Comment by pullmoll** [comment]
Hmm.. installing `gdb` and `flex-dbg` in the chroot and running `gdb flex` doesn't give me symbols in the backtrace:
```
(gdb) bt
#0  0x00000001000253ea in ?? ()
#1  0x0000000100026272 in ?? ()
#2  0x00007fa0c4b47ff1 in __libc_start_main () from /usr/lib/libc.so.6
#3  0x000000010001a71a in ?? ()
```
What am I doing wrong?

**Comment by pullmoll** [comment]
Ok, so `srcpkgs/flex/template` requires a fix for `glibc-2.26`:
```
CFLAGS="-D_GNU_SOURCE"
```
Otherwise the function `reallocarray()` isn't defined and leads to flex crashing later on.
See https://sourceware.org/bugzilla/show_bug.cgi?id=21789

**Comment by pullmoll** [comment]
I think that on the aarch64{,-musl} builders the cross-aarch64-linux-{gnu,musl} pkgs need to be built manually, because the builders don't use the main repository!?

**Comment by pullmoll** [comment]
The batch was built now - let's look for mor breakage caused by glibc-2.26
