### ISSUE TITLE
Tracking bug: build failures with gcc 5.4

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4351]
From a local fbulk, these are the errors that look like they result due to gcc 5.4.

Mostly changed inline semantics and the restrict keyword.

- [ ] argyllcms-1.8.3_2: numlib/numsup.h:327:32: error: expected declaration specifiers before 'error'
- [ ] brltty-5.3.1_1: gcj: error trying to exec 'ecj1': execvp: No such file or directory
- [ ] bwm-ng-0.6.1_1: undefined reference to `get_iface_stats'
- [ ] cclive-0.7.16_5: configure: error: invalid value: boost_major_version=
- [ ] cdecl-2.5_2: cdecl.c:248:24: error: expected identifier or '(' before 'restrict'
- [ ] csync-0.50.0_2: /builddir/csync-0.50.0/src/csync_log.h:58:23: error: ISO C does not support '__FUNCTION__' predefined identifie
- [x] devil-1.7.8_2: ./../src-IL/include/il_internal.h:230:54: error: expected ',' or '...' before 'FileName'
- [ ] foobillard++-3.42beta_2: billard3d.c:(.text+0x21c7): undefined reference to `fastcos'
- [x] freeimage-3.17.0_1: Source/LibWebP/./src/dsp/dsp.upsampling_mips_dsp_r2.c:37:34: error: invalid character ' ' in raw string delimiter
- [ ] gnubg: checking whether mmx is supported... ./configure: line 15967: 0xunknown: value too great for base (error token is "0xunknown")
- [ ] gtkglextmm-1.2.0_1: /usr/include/glibmm-2.4/glibmm/weakref.h:442:65: error: expected initializer bef
- [ ] ore 'noexcept'
- [ ] gummiboot-48_2: /usr/include/efi/x86_64/efibind.h:88:24: fatal error: stdint.h: No such file or directory
- [ ] hardinfo-0.5.1_4: /builddir/hardinfo-0.5.1/shell.c:921: undefined reference to `strend'
- [ ] ifenslave-1.1.0_6: /void-packages/srcpkgs/ifenslave/files/ifenslave.c:168:9: error: unknown type name 'uint32_t'
- [ ] ispc-1.9.0_1: cc1plus: error: unrecognized command line option '-Wno-deprecated-register' [-Werror]
- [ ] john-1.8.0_6: dynamic_fmt.c:(.text+0x80dc): undefined reference to `MD5_body_for_thread'
- [x] libcmis-0.5.0_3: configure: error: invalid value: boost_major_version=
- [x] libdvbpsi-1.1.2_3: test_dr.h:102:39: error: comparison of constant '12' with boolean expression is always true [-Werror=bool-compare]
- [ ] libewf-20140608_1: libuna_utf8_string.c:(.text+0x3267): undefined reference to `libuna_unicode_character_copy_from_utf32_stream'
- [ ] libgdlmm-3.7.3_2: dockobject.cc:117:7: error: 'exception_handlers_invoke' is not a member of 'Glib
- [ ] libpar2-0.4_1: /usr/include/sigc++-2.0/sigc++/functors/slot.h:215:72: error: 'operator()' not defined
- [ ] ltris-1.0.19_2: menu.c:(.text+0x665): undefined reference to `strequal'
- [ ] mDNSResponder-567_1: ../mDNSShared/dnsextd_parser.y:448:8: error: too many arguments to function 'yyparse'
- [ ] nitrogen-1.5.2_4: /usr/include/c++/5.4/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
- [ ] openmsx-0.12.0_2: src/RTScheduler.cc:34:72: error: no matching function for call to 'end(const openmsx::SchedulerQueue<openmsx::RTSyncPoint>&)'
- [ ] pavucontrol-3.0_2: /usr/include/sigc++-2.0/sigc++/functors/slot_base.h:119:15: warning: inline function 'void sigc::internal::slot_rep::set_parent(void*, sigc::internal::hook)' used but never defined
- [ ] ponyc-0.1.7_1: src/libponyc/debug/symbols.cc:426:21: error: 'debug_frame_t {aka struct debug_frame_t}' has no member named 'scope'
- [ ] python-crypto-2.6.1_5: configure: error: cannot run C compiled programs.
- [ ] rcs-5.9.4_2: base.h:757:6: error: old-style parameter declarations in prototyped function definition
- [ ] reiserfsprogs-3.6.24_2: reiserfslib.c:(.text+0x26bf): undefined reference to `misc_device_mode'
- [ ] soundmodem-0.18_1: genpamtbl.c:(.text+0xe04): undefined reference to `log_verblevel'
- [ ] schroot-1.7.2_6: /builddir/schroot-1.7.2/test/sbuild/keyfile.cc:72:3: error: no matching function for call to 'testing::AssertionResult::AssertionResult(std::ifstream&)'
- [ ] trousers-0.3.13_2: ps_utils.c:(.text+0x3c8): undefined reference to `write_data'
- [ ] xar-1.5.2_9: lib/ext2.c:229:12: error: 'EXT2_ECOMPR_FL' undeclared (first use in this function)
- [ ] zathura-pdf-mupdf-0.3.0_2: plugin.h:24:3: error: unknown type name 'fz_text_sheet'

**Comment by pullmoll** [comment]
I found a fix or workaround for libcmis:
```
# Fix build with gcc-5.4.0
boost_cv_lib_version=$(grep "#define BOOST_LIB_VERSION" \
        ${XBPS_CROSS_BASE}/usr/include/boost/version.hpp | \
        cut -d'"' -f2)
export boost_cv_lib_version
```

**Comment by pullmoll** [comment]
A fix for libdvbpsi boolean tests is this patch `srcpkgs/libdvbpsi/patches/fix-boolean_test.patch`
```
--- misc/test_dr.h      2013-11-10 13:13:35.000000000 +0100
+++ misc/test_dr.h      2016-08-28 19:54:18.243417859 +0200
@@ -93,13 +93,13 @@
   {                                                                     \
     fprintf(stdout, "  \"%s\" boolean check\n", #name);                 \
     i_loop_count = 0;                                                   \
-    s_decoded.name = 0;                                                 \
+    s_decoded.name = false;                                             \
     do                                                                  \
     {

 #define BOZO_end_boolean(name)                                          \
-      s_decoded.name += 12;                                             \
-    } while(!i_err && (s_decoded.name <= 12));                          \
+      s_decoded.name = !s_decoded.name;                                 \
+    } while(!i_err && s_decoded.name);                                  \
     fprintf(stdout, "\r  iteration count: %22llu", i_loop_count);       \
     if(i_err)                                                           \
       fprintf(stdout, "    FAILED !!!\n");                              \
```

**Comment by pullmoll** [comment]
Updated `cross-i686-pc-linux-gnu` to gcc-5.4.0 and get this error late in the build:
```
../sysdeps/unix/sysv/linux/posix_fallocate64.c: In function '__posix_fallocate64_l64':
../sysdeps/unix/sysv/linux/posix_fallocate64.c:42:1: error: bp cannot be used in asm here
```
and similar errors. It seems as if the assembler being used here isn't `i686-pc-linux-gnu-as`, but just `as` and thus does not know about the `bp` register.

**Comment by pullmoll** [comment]
Patch for `freeimage`: [fix-mips_dsp_r2.patch](http://misc.voidlinux.de/fix-mips_dsp_r2.patch)

**Comment by pullmoll** [comment]
I put packages built with a gcc-5.4.0 bootstrapped system on http://repo.voidlinux.de/current

Is there a HOWTO describing how to create a repository key (xx:yy:zz:....plib) for `/var/db/xbps/keys` from the public key of a private key used to sign those packages? I would like to create some live ISOs for testing which can download additional packages from that repo.

**Comment by Gottox** [comment]
obsolete. #4825
