### ISSUE TITLE
Gajim: authentication error, problem with python-nbxmpp

### ISSUE THREAD

**Issue by ernierasta** [voidlinux/void-packages#9653]
### System

* xuname:  
  Void 4.13.15_1 x86_64-musl AuthenticAMD uptodate rF
* package:  
  gajim-0.16.8_2, python-nbxmpp-0.6.0_1

### Expected behavior
authenticate on remote jabber server

### Actual behavior
Error, I am not able to login:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nbxmpp/idlequeue.py", line 549, in _process_events
    return IdleQueue._process_events(self, fd, flags)
  File "/usr/lib/python2.7/site-packages/nbxmpp/idlequeue.py", line 409, in _process_events
    obj.pollin()
  File "/usr/lib/python2.7/site-packages/nbxmpp/transports_nb.py", line 446, in pollin
    self._do_receive()
  File "/usr/lib/python2.7/site-packages/nbxmpp/transports_nb.py", line 669, in _do_receive
    self._on_receive(received)
  File "/usr/lib/python2.7/site-packages/nbxmpp/transports_nb.py", line 683, in _on_receive
    self.on_receive(data)
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 332, in <lambda>
    self.onreceive(lambda _data:self._xmpp_connect_machine(mode, _data))
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 366, in _xmpp_connect_machine
    self._xmpp_connect_machine(mode='STREAM_STARTED')
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 388, in _xmpp_connect_machine
    self._on_stream_start()
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 424, in _on_stream_start
    self._on_connect()
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 461, in _on_connect
    self.on_connect(self, self.connected)
  File "/usr/lib/python2.7/site-packages/gajim/common/connection.py", line 1428, in _connect_success
    return self.connection_accepted(con, con_type)
  File "/usr/lib/python2.7/site-packages/gajim/common/connection.py", line 1520, in connection_accepted
    resource=self.server_resource, sasl=True, on_auth=self.__on_auth, auth_mechs=auth_mechs)
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 510, in auth
    self._on_doc_attrs()
  File "/usr/lib/python2.7/site-packages/nbxmpp/client_nb.py", line 541, in _on_doc_attrs
    self._auth_mechs).PlugIn(self)
  File "/usr/lib/python2.7/site-packages/nbxmpp/plugin.py", line 65, in PlugIn
    return self.plugin(owner)
  File "/usr/lib/python2.7/site-packages/nbxmpp/auth_nb.py", line 134, in plugin
    self._owner.Dispatcher.Stream.features)
  File "/usr/lib/python2.7/site-packages/nbxmpp/auth_nb.py", line 208, in FeaturesHandler
    self.MechanismHandler()
  File "/usr/lib/python2.7/site-packages/nbxmpp/auth_nb.py", line 256, in MechanismHandler
    self._owner._caller.get_password(self.set_password, self.mechanism)
  File "/usr/lib/python2.7/site-packages/gajim/common/connection.py", line 2945, in get_password
    self.set_password(self.password)
  File "/usr/lib/python2.7/site-packages/gajim/common/connection.py", line 2959, in set_password
    callback(password)
  File "/usr/lib/python2.7/site-packages/nbxmpp/auth_nb.py", line 501, in set_password
    self.client_nonce = '%x' % rndg.getrandbits(196)
  File "/usr/lib/python2.7/site-packages/nbxmpp/rndg.py", line 46, in getrandbits
    random_str = OpenSSL.rand.bytes(bytes)
AttributeError: 'module' object has no attribute 'bytes'

### Steps to reproduce the behavior
Run gajim.

### Possible solutions

Maybe pull request #9647 will solve it?

It is problem with python-nbxmpp, on Archlinux they patched it:
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nbxmpp&id=00e9aa8ba1fe2b9acf4093ab6c9956bf68cde43f

Here is bug report:
https://bugs.archlinux.org/task/56488

**Comment by maxice8** [comment]
Should problably work with the new 0.6.1 version that removes random number generation. https://github.com/voidlinux/void-packages/pull/9647

**Comment by maxice8** [comment]
Seems to work here with the new version.

**Comment by maxice8** [comment]
0.6.1 was merged, can you test if it works ?

**Comment by ernierasta** [comment]
Yes, it works ok now. Thank you!
