### ISSUE TITLE
broadcom-wl-dkms: failed to build on kernel 3.19.0.

### ISSUE THREAD

**Issue by rtlanceroad** [voidlinux/void-packages#994]
As titled. Full build log is listed below:

[lee@voidbox ~]$ cat /var/lib/dkms/wl/6.30.223.248/build/make.log 
DKMS make.log for wl-6.30.223.248 for kernel 3.19.0_1 (x86_64)
Fri Feb 20 22:57:02 CST 2015
make: Entering directory '/usr/src/kernel-headers-3.19.0_1'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/wl/6.30.223.248/build/built-in.o
  CC [M]  /var/lib/dkms/wl/6.30.223.248/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.o
/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.c: In function ‘wl_alloc_linux_if’:
/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.c:1310:64: error: macro "alloc_netdev" requires 4 arguments, but only 3 given
  dev = alloc_netdev(sizeof(priv_link_t), intf_name, ether_setup);
                                                                ^
/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.c:1310:8: error: ‘alloc_netdev’ undeclared (first use in this function)
  dev = alloc_netdev(sizeof(priv_link_t), intf_name, ether_setup);
        ^
/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.c:1310:8: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:257: recipe for target '/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.o' failed
make[1]: *** [/var/lib/dkms/wl/6.30.223.248/build/src/wl/sys/wl_linux.o] Error 1
Makefile:1382: recipe for target '_module_/var/lib/dkms/wl/6.30.223.248/build' failed
make: *** [_module_/var/lib/dkms/wl/6.30.223.248/build] Error 2
make: Leaving directory '/usr/src/kernel-headers-3.19.0_1'

**Comment by mid-kid** [comment]
I just compile it manually.
[This](https://aur.archlinux.org/packages/broadcom-wl-dkms/) package in the AUR has patches and a source URL for this.

**Comment by rtlanceroad** [comment]
@mid-kid  You are right. Both Arch and Gentoo have patches for it.  But it's better to fix in void repo :)

**Comment by xtraeme** [comment]
Waiting for someone to contribute the patches to our pkg :-)

**Comment by necrophcodr** [comment]
I had this issue as well. Had the issue in Funtoo as well, and when using Void Linux I worked around it by using b43-fwcutter.
However, some patches to make it work would be great. I might look into this later this week or so, if no one else cares to do it.
