### PR TITLE
btrfs-progs: fix build with e2fsprogs-1.44.0

### LINKED ISSUE #12624: btrfs-progs: build broken
```
=> btrfs-progs-4.15.1_1: running pre_build ...
=> btrfs-progs-4.15.1_1: running do_build ...
    [AR]     libbtrfs.a
    [LN]     libbtrfs.so.0
    [CC]     convert/source-ext2.o
    [LN]     libbtrfs.so
Making all in Documentation
    [LD]     btrfs
    [LD]     mkfs.btrfs
    [LD]     btrfs-debug-tree
    [ASCII]  btrfs-ioctl.xml
    [LD]     btrfs-map-logical
    [LD]     btrfs-image
    [ASCII]  btrfs-man5.xml
    [LD]     btrfs-zero-log
    [LD]     btrfs-find-root
    [LD]     btrfstune
    [LD]     btrfs-select-super
    [LN]     btrfsck
    [LD]     btrfs-corrupt-block
    [LD]     libbtrfs.so.0.1
In file included from convert/source-ext2.c:19:0:
./kerncompat.h:39:0: warning: "__always_inline" redefined
 #define __always_inline __inline __attribute__ ((__always_inline__))

In file included from /usr/include/linux/posix_types.h:4:0,
                 from /usr/include/linux/types.h:8,
                 from ./kerncompat.h:30,
                 from convert/source-ext2.c:19:
/usr/include/linux/stddef.h:4:0: note: this is the location of the previous definition
 #define __always_inline __inline__

convert/source-ext2.c: In function 'ext2_xattr_check_entry':
convert/source-ext2.c:425:13: error: 'struct ext2_ext_attr_entry' has no member named 'e_value_block'; did you mean 'e_value_offs'?
  if (entry->e_value_block != 0 || value_size > size ||
             ^~~~~~~~~~~~~
             e_value_offs
make: *** [Makefile:282: convert/source-ext2.o] Error 1
make: *** Waiting for unfinished jobs....
    [XMLTO]  btrfs-ioctl.3
    [GZ]     btrfs-ioctl.3.gz
    [XMLTO]  btrfs-man5.5
    [GZ]     btrfs-man5.5.gz
rm btrfs-man5.5 btrfs-man5.xml btrfs-ioctl.3 btrfs-ioctl.xml
=> ERROR: btrfs-progs-4.15.1_1: failed to run do_build() at line 13.
```

### PR DESCRIPTION
**Pull request by maxice8**
resolves #12624 if you merge this please close

check Issue above for links to Kernel Bugzilla, btrfs-progs issue.

### CODE REVIEW

**Comment by ebfe** [comment]
6859d1cbe22539a8409ad2bf7e7e8b26a4bd39ff
